version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: danieldatabase
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: danielpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./python_app
    container_name: python_app_container
    environment:
      - DB_NAME=danieldatabase
      - DB_USER=daniel
      - DB_PASSWORD=danielpassword
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres

volumes:
  postgres_data: # By default, the volume is located at /var/lib/docker/volumes
